# Generated by Django 2.0.4 on 2018-05-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Название')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('work__title', 'student__group', 'student__surname', 'student__name', 'student__patronymic'),
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('AT', 'Ассистент'), ('TT', 'Преподаватель'), ('ST', 'Старший преподаватель'), ('AP', 'Доцент'), ('PP', 'Профессор')], default='TT', max_length=2, verbose_name='Должность')),
                ('title', models.CharField(blank=True, choices=[('DT', 'Доктор технических наук'), ('CT', 'Кандидат технических наук'), ('DPHM', 'Доктор физико-математических наук'), ('CPHM', 'Кандидат физико-математических наук'), ('DE', 'Доктор экономических наук'), ('CE', 'Кандидат экономических наук'), ('DP', 'Доктор педагогических наук'), ('CP', 'Кандидат педагогических наук')], max_length=4, verbose_name='Звание')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Информация')),
            ],
            options={
                'ordering': ('surname', 'name', 'patronymic'),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('group', models.CharField(choices=[('11', 'ИУ7-11'), ('12', 'ИУ7-12'), ('13', 'ИУ7-13'), ('14', 'ИУ7-14'), ('15', 'ИУ7-15'), ('16', 'ИУ7-16'), ('21', 'ИУ7-21'), ('22', 'ИУ7-22'), ('23', 'ИУ7-23'), ('24', 'ИУ7-24'), ('25', 'ИУ7-25'), ('26', 'ИУ7-26'), ('31', 'ИУ7-31'), ('32', 'ИУ7-32'), ('33', 'ИУ7-33'), ('34', 'ИУ7-34'), ('35', 'ИУ7-35'), ('36', 'ИУ7-36'), ('41', 'ИУ7-41'), ('42', 'ИУ7-42'), ('43', 'ИУ7-43'), ('44', 'ИУ7-44'), ('45', 'ИУ7-45'), ('46', 'ИУ7-46'), ('51', 'ИУ7-51'), ('52', 'ИУ7-52'), ('53', 'ИУ7-53'), ('54', 'ИУ7-54'), ('55', 'ИУ7-55'), ('56', 'ИУ7-56'), ('61', 'ИУ7-61'), ('62', 'ИУ7-62'), ('63', 'ИУ7-63'), ('64', 'ИУ7-64'), ('65', 'ИУ7-65'), ('66', 'ИУ7-66'), ('71', 'ИУ7-71'), ('72', 'ИУ7-72'), ('73', 'ИУ7-73'), ('74', 'ИУ7-74'), ('75', 'ИУ7-75'), ('76', 'ИУ7-76'), ('81', 'ИУ7-81'), ('82', 'ИУ7-82'), ('83', 'ИУ7-83'), ('84', 'ИУ7-84'), ('85', 'ИУ7-85'), ('86', 'ИУ7-86'), ('11М', 'ИУ7-11М'), ('12М', 'ИУ7-12М'), ('13М', 'ИУ7-13М'), ('14М', 'ИУ7-14М'), ('15М', 'ИУ7-15М'), ('16М', 'ИУ7-16М'), ('21М', 'ИУ7-21М'), ('22М', 'ИУ7-22М'), ('23М', 'ИУ7-23М'), ('24М', 'ИУ7-24М'), ('25М', 'ИУ7-25М'), ('26М', 'ИУ7-26М'), ('31М', 'ИУ7-31М'), ('32М', 'ИУ7-32М'), ('33М', 'ИУ7-33М'), ('34М', 'ИУ7-34М'), ('35М', 'ИУ7-35М'), ('36М', 'ИУ7-36М'), ('41М', 'ИУ7-41М'), ('42М', 'ИУ7-42М'), ('43М', 'ИУ7-43М'), ('44М', 'ИУ7-44М'), ('45М', 'ИУ7-45М'), ('46М', 'ИУ7-46М')], default='11', max_length=3, verbose_name='Группа')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('personal_preferences', models.ManyToManyField(blank=True, to='distribution_app.Mentor', verbose_name='Личные предпочтения')),
                ('science_preferences', models.ManyToManyField(blank=True, to='distribution_app.Direction', verbose_name='Научные предпочтения')),
            ],
            options={
                'ordering': ('group', 'surname', 'name', 'patronymic'),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Название')),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('1М', '1М'), ('2М', '2М')], default='1', max_length=2, verbose_name='Курс')),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1, verbose_name='Семестр')),
                ('directions', models.ManyToManyField(blank=True, to='distribution_app.Direction', verbose_name='Направления')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='mentor',
            name='personal_preferences',
            field=models.ManyToManyField(blank=True, to='distribution_app.Student', verbose_name='Личные предпочтения'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='science_preferences',
            field=models.ManyToManyField(blank=True, to='distribution_app.Direction', verbose_name='Научные предпочтения'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution_app.Mentor'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution_app.Student'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution_app.Work'),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together={('work', 'student')},
        ),
    ]
