# Generated by Django 2.0.4 on 2018-05-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('title',), 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
